### ISSUE TITLE
"$ rake websocket_rails:start_server  RAILS_ENV=production" fail

### ISSUE THREAD

**Issue by FTAndy** [websocket-rails/websocket-rails#263]
My app is deployed to nginx + passenger.
So i try to test websocket-rail in my local  production ENV.
Before i start passenger, i try to "$ rake websocket_rails:start_server  RAILS_ENV=production".
So it turns out "Websocket Rails Standalone Server listening on port 3005".(I use port 3005)
It seems work well.But when i try to "$ netstat -ntlp | grep LISTEN".The listening port 3005 is not there.
I try again "$ rake websocket_rails:start_server  RAILS_ENV=production".
It turns again "Websocket Rails Standalone Server listening on port 3005".WTF!
It looks like my localhost port 3005 do not open?Or maybe this problem is caused by other reason.
I think some guys will know.Please help me.

**Comment by upender-devulapally** [comment]
+1

**Comment by JerryGreen** [comment]
Same here. But I use 3001 default port, not 3005. No errors in output and no running process too.

**Comment by JerryGreen** [comment]
Btw, it's production issue (I am using Puma there). On development machine It's ok (standalone server successfully running with `rake websocket_rails:start_server`). It's all the production side (and production environment).

In websocket_rails.log I got this:

```
Writing PID to /home/ascii-rpg-server/app/releases/13/tmp/pids/websocket_rails.pid
Thin web server (v1.6.4 codename Gob Bluth)
Maximum connections set to 1024
Listening on 0.0.0.0:3001, CTRL+C to stop
Exiting!
/home/ascii-rpg-server/app/releases/13/vendor/bundle/ruby/2.2.0/gems/redis-3.2.2/lib/redis/client.rb:332:in `rescue in establish_connection': Error connecting to Redis on 127.0.0.1:6379 (Errno::ECONNREFUSED) (Redis::CannotConnectError)
        from /home/ascii-rpg-server/app/releases/13/vendor/bundle/ruby/2.2.0/gems/redis-3.2.2/lib/redis/client.rb:318:in `establish_connection'
        from /home/ascii-rpg-server/app/releases/13/vendor/bundle/ruby/2.2.0/gems/redis-3.2.2/lib/redis/client.rb:94:in `block in connect'
        from /home/ascii-rpg-server/app/releases/13/vendor/bundle/ruby/2.2.0/gems/redis-3.2.2/lib/redis/client.rb:280:in `with_reconnect'
        from /home/ascii-rpg-server/app/releases/13/vendor/bundle/ruby/2.2.0/gems/redis-3.2.2/lib/redis/client.rb:93:in `connect'
        from /home/ascii-rpg-server/app/releases/13/vendor/bundle/ruby/2.2.0/gems/redis-3.2.2/lib/redis/client.rb:351:in `ensure_connected'
        from /home/ascii-rpg-server/app/releases/13/vendor/bundle/ruby/2.2.0/gems/redis-3.2.2/lib/redis/client.rb:208:in `block in process'
        from /home/ascii-rpg-server/app/releases/13/vendor/bundle/ruby/2.2.0/gems/redis-3.2.2/lib/redis/client.rb:293:in `logging'
```

As I see now - I must use redis if I want to enable standalone mode. But I'm not sure I need standalone mode. Do I really need that for Puma?
