### ISSUE TITLE
Cannot install hiredis in order to use websocket

### ISSUE THREAD

**Issue by emmanuelmillionaer** [websocket-rails/websocket-rails#286]
I bought me a new Windows 8.1 computer. Now i tried to run my old rails projects.  In on of them i'm using websockets. The gem 'websocket' is reqiurirng `hiredis`

So i tried to install it but i get error always this error: 

```
C:\project_s2_Development\project_s2apiheroku2>gem install hiredis
Temporarily enhancing PATH to include DevKit...
Building native extensions.  This could take a while...
ERROR:  Error installing hiredis:
        ERROR: Failed to build gem native extension.

    C:/RailsInstaller/Ruby2.1.0/bin/ruby.exe extconf.rb
gcc -std=c99 -pedantic -c -O3 -fPIC  -Wall -W -Wstrict-prototypes -Wwrite-string
s -g -ggdb  net.c
net.c:1:0: warning: -fPIC ignored for target (all code is position independent)
[enabled by default]
net.c:35:24: fatal error: sys/socket.h: No such file or directory
compilation terminated.
make: *** [net.o] Error 1
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
        --with-opt-dir
        --without-opt-dir
        --with-opt-include
        --without-opt-include=${opt-dir}/include
        --with-opt-lib
        --without-opt-lib=${opt-dir}/lib
        --with-make-prog
        --without-make-prog
        --srcdir=.
        --curdir
        --ruby=C:/RailsInstaller/Ruby2.1.0/bin/ruby
extconf.rb:25:in `block in <main>': Building hiredis failed (RuntimeError)
        from extconf.rb:23:in `chdir'
        from extconf.rb:23:in `<main>'

extconf failed, exit code 1

Gem files will remain installed in C:/RailsInstaller/Ruby2.1.0/lib/ruby/gems/2.1
.0/gems/hiredis-0.5.2 for inspection.
Results logged to C:/RailsInstaller/Ruby2.1.0/lib/ruby/gems/2.1.0/extensions/x86
-mingw32/2.1.0/hiredis-0.5.2/gem_make.out
```

Can you recommend something how to install hiredis on windows? I cannot find anything! Thanks for your help!

**Comment by zaingz** [comment]
Bad news fella, hiredis doesn't work on windows.
http://stackoverflow.com/questions/8234493/error-when-bundle-install-on-windows/8235541#8235541
