### ISSUE TITLE
block in find_user

### ISSUE THREAD

**Issue by u2** [websocket-rails/websocket-rails#304]
Sometime the websocket-rails will crash and I find the last error log in websocket_rails_server.log is like this.
```
/var/app/chat/current/vendor/bundle/ruby/2.1.0/gems/json-1.8.2/lib/json/common.rb:155:in `initialize': no implicit conversion of Fixnum into String (TypeError)

from /var/app/chat/current/vendor/bundle/ruby/2.1.0/gems/json-1.8.2/lib/json/common.rb:155:in `new'

from /var/app/chat/current/vendor/bundle/ruby/2.1.0/gems/json-1.8.2/lib/json/common.rb:155:in `parse'

from /var/app/chat/current/vendor/bundle/ruby/2.1.0/bundler/gems/websocket-rails-712fd4e35325/lib/websocket_rails/synchronization.rb:167:in `block in find_user'
```
My websocket config file.
```
WebsocketRails.setup do |config|

  # Uncomment to override the default log level. The log level can be
  # any of the standard Logger log levels. By default it will mirror the
  # current Rails environment log level.
  config.log_level = :error

  # Uncomment to change the default log file path.
  # config.log_path = "#{Rails.root}/log/websocket_rails.log"
  config.log_path = "#{Rails.root}/log/chat.log"


  # Set to true if you wish to log the internal websocket_rails events
  # such as the keepalive `websocket_rails.ping` event.
  config.log_internal_events = false

  # Change to true to enable standalone server mode
  # Start the standalone server with rake websocket_rails:start_server
  # * Requires Redis
  config.standalone = true

  # Change to true to enable channel synchronization between
  # multiple server instances.
  # * Requires Redis.
  config.synchronize = true

  # Uncomment and edit to point to a different redis instance.
  # Will not be used unless standalone or synchronization mode
  # is enabled.
  # config.redis_options = {:host => 'localhost', :port => '6379', :password => 's*78_uibz&0n1Z' }

  # By default, all subscribers in to a channel will be removed
  # when that channel is made private. If you don't wish active
  # subscribers to be removed from a previously public channel
  # when making it private, set the following to true.
  # config.keep_subscribers_when_private = false

  # Used as the key for the WebsocketRails.users Hash. This method
  # will be called on the `current_user` object in your controller
  # if one exists. If `current_user` does not exist or does not
  # respond to the identifier, the key will default to `connection.id`
  # config.user_identifier = :id
end
```
I guess there are some dirty data in redis, so I find find all websocket_rails.users and then JSON.parse the raw_user,but it success.
```
result = redis.hgetall('websocket_rails.users')
result.each{|i| JSON.parse i[1] }
```
This error only can appear on our production env sometime, but cannot reappear local.And we did not insert or write manually anything data to websocket_rails.users.

**Comment by Samhane** [comment]
I have the same problem. Tried to fix it: https://github.com/Samhane/websocket-rails/commit/88b2ff38de6c6e9cb0409eea9e9236634e322a87
But I get second problem: unexpected token at 'fbbcfcbc-cfea-4abc-b170-52934a458a5a', what caused in `JSON.parse(raw_user)`

After flush redis db working correct
