### ISSUE TITLE
websocket-rails crash

### ISSUE THREAD

**Issue by u2** [websocket-rails/websocket-rails#305]
Sometime the websocket-rails will crash and I find the last error log in websocket_rails_server.log is like this.
```
/var/app/chat/current/vendor/bundle/ruby/2.1.0/bundler/gems/websocket-rails-712fd4e35325/lib/websocket_rails/connection_adapters/web_socket.rb:21:in `send': undefined method `[["websocket_rails.ping",{"id":null,"channel":null,"user_id":null,"data":{},"success":null,"result":null,"token":null,"server_token":null}]]' for nil:NilClass (NoMethodError)

from /var/app/chat/current/vendor/bundle/ruby/2.1.0/bundler/gems/websocket-rails-712fd4e35325/lib/websocket_rails/connection_adapters.rb:77:in `trigger'

from /var/app/chat/current/vendor/bundle/ruby/2.1.0/bundler/gems/websocket-rails-712fd4e35325/lib/websocket_rails/connection_adapters.rb:184:in `block in start_ping_timer'

from /var/app/chat/current/vendor/bundle/ruby/2.1.0/gems/eventmachine-1.0.4/lib/em/timers.rb:56:in `call'

from /var/app/chat/current/vendor/bundle/ruby/2.1.0/gems/eventmachine-1.0.4/lib/em/timers.rb:56:in `fire'

from /var/app/chat/current/vendor/bundle/ruby/2.1.0/gems/eventmachine-1.0.4/lib/eventmachine.rb:187:in `call'

from /var/app/chat/current/vendor/bundle/ruby/2.1.0/gems/eventmachine-1.0.4/lib/eventmachine.rb:187:in `run_machine'

from /var/app/chat/current/vendor/bundle/ruby/2.1.0/gems/eventmachine-1.0.4/lib/eventmachine.rb:187:in `run'

from /var/app/chat/current/vendor/bundle/ruby/2.1.0/gems/thin-1.6.3/lib/thin/backends/base.rb:73:in `start'

from /var/app/chat/current/vendor/bundle/ruby/2.1.0/gems/thin-1.6.3/lib/thin/server.rb:162:in `start'

from /var/app/chat/current/vendor/bundle/ruby/2.1.0/gems/thin-1.6.3/lib/thin/controllers/controller.rb:87:in `start'

from /var/app/chat/current/vendor/bundle/ruby/2.1.0/bundler/gems/websocket-rails-712fd4e35325/lib/rails/tasks/websocket_rails.tasks:14:in `block (3 levels) in <top (required)>'

from /var/app/chat/current/vendor/bundle/ruby/2.1.0/bundler/gems/websocket-rails-712fd4e35325/lib/rails/tasks/websocket_rails.tasks:13:in `fork'

from /var/app/chat/current/vendor/bundle/ruby/2.1.0/bundler/gems/websocket-rails-712fd4e35325/lib/rails/tasks/websocket_rails.tasks:13:in `block (2 levels) in <top (required)>'

from /var/app/chat/current/vendor/bundle/ruby/2.1.0/gems/rake-10.4.2/lib/rake/task.rb:240:in `call'

from /var/app/chat/current/vendor/bundle/ruby/2.1.0/gems/rake-10.4.2/lib/rake/task.rb:240:in `block in execute'

from /var/app/chat/current/vendor/bundle/ruby/2.1.0/gems/rake-10.4.2/lib/rake/task.rb:235:in `each'

from /var/app/chat/current/vendor/bundle/ruby/2.1.0/gems/rake-10.4.2/lib/rake/task.rb:235:in `execute'

from /var/app/chat/current/vendor/bundle/ruby/2.1.0/gems/rake-10.4.2/lib/rake/task.rb:179:in `block in invoke_with_call_chain'

from /home/god/.rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/monitor.rb:211:in `mon_synchronize'

from /var/app/chat/current/vendor/bundle/ruby/2.1.0/gems/rake-10.4.2/lib/rake/task.rb:172:in `invoke_with_call_chain'

from /var/app/chat/current/vendor/bundle/ruby/2.1.0/gems/rake-10.4.2/lib/rake/task.rb:165:in `invoke'

from /var/app/chat/current/vendor/bundle/ruby/2.1.0/gems/rake-10.4.2/lib/rake/application.rb:150:in `invoke_task'

from /var/app/chat/current/vendor/bundle/ruby/2.1.0/gems/rake-10.4.2/lib/rake/application.rb:106:in `block (2 levels) in top_level'

from /var/app/chat/current/vendor/bundle/ruby/2.1.0/gems/rake-10.4.2/lib/rake/application.rb:106:in `each'

from /var/app/chat/current/vendor/bundle/ruby/2.1.0/gems/rake-10.4.2/lib/rake/application.rb:106:in `block in top_level'

from /var/app/chat/current/vendor/bundle/ruby/2.1.0/gems/rake-10.4.2/lib/rake/application.rb:115:in `run_with_threads'

from /var/app/chat/current/vendor/bundle/ruby/2.1.0/gems/rake-10.4.2/lib/rake/application.rb100in `top_level'

from /var/app/chat/current/vendor/bundle/ruby/2.1.0/gems/rake-10.4.2/lib/rake/application.rb:78:in `block in run'

from /var/app/chat/current/vendor/bundle/ruby/2.1.0/gems/rake-10.4.2/lib/rake/application.rb:176:in `standard_exception_handling'

from /var/app/chat/current/vendor/bundle/ruby/2.1.0/gems/rake-10.4.2/lib/rake/application.rb:75:in `run'

from /var/app/chat/current/vendor/bundle/ruby/2.1.0/gems/rake-10.4.2/bin/rake:33:in `<top (required)>'

from /var/app/chat/current/vendor/bundle/ruby/2.1.0/bin/rake:23:in `load'

from /var/app/chat/current/vendor/bundle/ruby/2.1.0/bin/rake:23:in `<main>'
```
My websocket config file.
```
WebsocketRails.setup do |config|

  # Uncomment to override the default log level. The log level can be
  # any of the standard Logger log levels. By default it will mirror the
  # current Rails environment log level.
  config.log_level = :error

  # Uncomment to change the default log file path.
  # config.log_path = "#{Rails.root}/log/websocket_rails.log"
  config.log_path = "#{Rails.root}/log/chat.log"


  # Set to true if you wish to log the internal websocket_rails events
  # such as the keepalive `websocket_rails.ping` event.
  config.log_internal_events = false

  # Change to true to enable standalone server mode
  # Start the standalone server with rake websocket_rails:start_server
  # * Requires Redis
  config.standalone = true

  # Change to true to enable channel synchronization between
  # multiple server instances.
  # * Requires Redis.
  config.synchronize = true

  # Uncomment and edit to point to a different redis instance.
  # Will not be used unless standalone or synchronization mode
  # is enabled.
  # config.redis_options = {:host => 'localhost', :port => '6379', :password => 's*78_uibz&0n1Z' }

  # By default, all subscribers in to a channel will be removed
  # when that channel is made private. If you don't wish active
  # subscribers to be removed from a previously public channel
  # when making it private, set the following to true.
  # config.keep_subscribers_when_private = false

  # Used as the key for the WebsocketRails.users Hash. This method
  # will be called on the `current_user` object in your controller
  # if one exists. If `current_user` does not exist or does not
  # respond to the identifier, the key will default to `connection.id`
  # config.user_identifier = :id
end
```
This error only can appear on our production env sometime, but cannot reappear local.

**Comment by amryousry92** [comment]
I have that same problem.

Have you found anything?

**Comment by u2** [comment]
https://github.com/websocket-rails/websocket-rails/issues/29
