### ISSUE TITLE
Redis error when sending two different messages

### ISSUE THREAD

**Issue by Ricardonacif** [websocket-rails/websocket-rails#313]
Hey guys,

On my websocket controller, if I trigger two different websocket events, I get an error message about redis and the server exits. Take a look:

```ruby
#the action of my websocket controller, triggered after an event
def action
  WebsocketRails['private_channel'].trigger 'received_chat_message', json #I'm sending to a priva channel here
  WebsocketRails.users[current_user.id].send_message('notify_received_message', 'other_message') #I'm sending to a specific user here
end

```
The weird thing is that If I comment one line out (doesn't matter which one), it doesn't give me any error. But if the two statements runs, I get:

```
/Users/ricardonacif/.rbenv/versions/1.9.3-p551/lib/ruby/gems/1.9.1/gems/redis-3.2.1/lib/redis/client.rb:331:in `rescue in establish_connection': Error connecting to Redis on localhost:6379 (Errno::ECONNREFUSED) (Redis::CannotConnectError)
	from /Users/ricardonacif/.rbenv/versions/1.9.3-p551/lib/ruby/gems/1.9.1/gems/redis-3.2.1/lib/redis/client.rb:317:in `establish_connection'
	from /Users/ricardonacif/.rbenv/versions/1.9.3-p551/lib/ruby/gems/1.9.1/gems/redis-3.2.1/lib/redis/client.rb:94:in `block in connect'
	from /Users/ricardonacif/.rbenv/versions/1.9.3-p551/lib/ruby/gems/1.9.1/gems/redis-3.2.1/lib/redis/client.rb:279:in `with_reconnect'
	from /Users/ricardonacif/.rbenv/versions/1.9.3-p551/lib/ruby/gems/1.9.1/gems/redis-3.2.1/lib/redis/client.rb:93:in `connect'
	from /Users/ricardonacif/.rbenv/versions/1.9.3-p551/lib/ruby/gems/1.9.1/gems/redis-3.2.1/lib/redis/client.rb:350:in `ensure_connected'
	from /Users/ricardonacif/.rbenv/versions/1.9.3-p551/lib/ruby/gems/1.9.1/gems/redis-3.2.1/lib/redis/client.rb:207:in `block in process'
	from /Users/ricardonacif/.rbenv/versions/1.9.3-p551/lib/ruby/gems/1.9.1/gems/redis-3.2.1/lib/redis/client.rb:292:in `logging'
	from /Users/ricardonacif/.rbenv/versions/1.9.3-p551/lib/ruby/gems/1.9.1/gems/redis-3.2.1/lib/redis/client.rb:206:in `process'
	from /Users/ricardonacif/.rbenv/versions/1.9.3-p551/lib/ruby/gems/1.9.1/gems/redis-3.2.1/lib/redis/client.rb:112:in `call'
	from /Users/ricardonacif/.rbenv/versions/1.9.3-p551/lib/ruby/gems/1.9.1/gems/redis-3.2.1/lib/redis.rb:1901:in `block in hget'
	from /Users/ricardonacif/.rbenv/versions/1.9.3-p551/lib/ruby/gems/1.9.1/gems/redis-3.2.1/lib/redis.rb:37:in `block in synchronize'
	from /Users/ricardonacif/.rbenv/versions/1.9.3-p551/lib/ruby/1.9.1/monitor.rb:211:in `mon_synchronize'
	from /Users/ricardonacif/.rbenv/versions/1.9.3-p551/lib/ruby/gems/1.9.1/gems/redis-3.2.1/lib/redis.rb:37:in `synchronize'
	from /Users/ricardonacif/.rbenv/versions/1.9.3-p551/lib/ruby/gems/1.9.1/gems/redis-3.2.1/lib/redis.rb:1900:in `hget'
	from /Users/ricardonacif/.rbenv/versions/1.9.3-p551/lib/ruby/gems/1.9.1/gems/websocket-rails-0.7.0/lib/websocket_rails/synchronization.rb:166:in `block in find_user'


```

This happens both in production and development. Any special reason?

**Comment by bmxpert1** [comment]
I'm having similar issues and have been getting around it by forcing the use of redis-rb version 3.2.0

**Comment by paulstraw** [comment]
I'm seeing the same issue, and forcing redis-rb 3.2.0 fixes it for me as well.

**Comment by paulstraw** [comment]
Hey @Ricardonacif, is there a particular reason you closed this? As far as I can tell, it's still a valid issue, no?

**Comment by Ricardonacif** [comment]
Opss, sorry. Reopening it. 

Btw, Redis isn't a dependency of the gem, right?

**Comment by kennethjohnbalgos** [comment]
@Ricardonacif, yes it's not a dependency but forcing to use Redis 3.2.0 solves the problem.
Thank you @bmxpert1 and @paulstraw!
```
gem 'redis', '3.2.0'
```

**Comment by ericdfields** [comment]
Bump. 3.2.0 Fixes a similar issue.

**Comment by moaa** [comment]
I made some changes to the way synchronization handles its data.  I've also added connection pool and redis-objects as dependencies.

Update your gemfile with the following: 
```gem 'websocket-rails', github: 'moaa/websocket-rails', branch: 'sync_fixes'```

**Comment by Ricardonacif** [comment]
Hey @moaa, thanks for the good work! Right now I'm using the branch threadsocket-rails-sync, what's the difference between this and your branch sync_fixes?

**Comment by moaa** [comment]
@Ricardonacif `sync_fixes` is the current master with some synchronization changes(fixed a rare race condition). The threadsocket-rails-sync is somewhat of a re-write, that branch removes EventMachine(thin) as a dependency and instead uses Puma.  The threadsocket branch also includes a lot of the sub-protocol support Dan did a while back.  

If you're really interested in the differences, you can have a look at the full commit history here: https://github.com/websocket-rails/websocket-rails/compare/master...moaa:threadsocket-rails

**Comment by Ricardonacif** [comment]
Got it! Thanks @moaa

**Comment by baldasman** [comment]
Hi @moaa, i am using branch sync_fixes and i am having some unexpected crashes as you can see in the logs bellow. It seems that some times there is a timeout when trying to get a connection from the pool. 

Can you help?

#websocket_rails.log

E [2015-06-24 14:26:53.506] [Dispatcher] Timeout::Error: Waited 5 sec
E [2015-06-24 14:26:53.507] [Dispatcher] /home/www-data/.rvm/gems/ruby-2.2.1/gems/connection_pool-2.2.0/lib/connection_pool/timed_stack.rb:85:in `block (2 levels) in pop'
E [2015-06-24 14:26:53.507] [Dispatcher] /home/www-data/.rvm/gems/ruby-2.2.1/gems/connection_pool-2.2.0/lib/connection_pool/timed_stack.rb:77:in `loop'
E [2015-06-24 14:26:53.507] [Dispatcher] /home/www-data/.rvm/gems/ruby-2.2.1/gems/connection_pool-2.2.0/lib/connection_pool/timed_stack.rb:77:in `block in pop'
E [2015-06-24 14:26:53.507] [Dispatcher] /home/www-data/.rvm/gems/ruby-2.2.1/gems/connection_pool-2.2.0/lib/connection_pool/timed_stack.rb:76:in `synchronize'
E [2015-06-24 14:26:53.507] [Dispatcher] /home/www-data/.rvm/gems/ruby-2.2.1/gems/connection_pool-2.2.0/lib/connection_pool/timed_stack.rb:76:in `pop'
E [2015-06-24 14:26:53.507] [Dispatcher] /home/www-data/.rvm/gems/ruby-2.2.1/gems/connection_pool-2.2.0/lib/connection_pool.rb:89:in `checkout'
E [2015-06-24 14:26:53.507] [Dispatcher] /home/www-data/.rvm/gems/ruby-2.2.1/gems/connection_pool-2.2.0/lib/connection_pool.rb:61:in `block in with'
E [2015-06-24 14:26:53.507] [Dispatcher] /home/www-data/.rvm/gems/ruby-2.2.1/gems/connection_pool-2.2.0/lib/connection_pool.rb:60:in `handle_interrupt'
E [2015-06-24 14:26:53.507] [Dispatcher] /home/www-data/.rvm/gems/ruby-2.2.1/gems/connection_pool-2.2.0/lib/connection_pool.rb:60:in `with'
E [2015-06-24 14:26:53.507] [Dispatcher] /home/www-data/.rvm/gems/ruby-2.2.1/gems/connection_pool-2.2.0/lib/connection_pool.rb:131:in `with'
E [2015-06-24 14:26:53.507] [Dispatcher] /home/www-data/.rvm/gems/ruby-2.2.1/gems/connection_pool-2.2.0/lib/connection_pool.rb:143:in `method_missing'
E [2015-06-24 14:26:53.507] [Dispatcher] /home/www-data/.rvm/gems/ruby-2.2.1/gems/redis-objects-1.2.0/lib/redis/hash_key.rb:29:in `hget'
E [2015-06-24 14:26:53.507] [Dispatcher] /home/www-data/.rvm/gems/ruby-2.2.1/bundler/gems/websocket-rails-1b81a919731b/lib/websocket_rails/channel.rb:62:in `token'
E [2015-06-24 14:26:53.507] [Dispatcher] /home/www-data/.rvm/gems/ruby-2.2.1/bundler/gems/websocket-rails-1b81a919731b/lib/websocket_rails/channel.rb:31:in `trigger'
E [2015-06-24 14:26:53.508] [Dispatcher] /home/www-data/.rvm/gems/ruby-2.2.1/bundler/gems/websocket-rails-1b81a919731b/lib/websocket_rails/channel.rb:18:in `subscribe'
E [2015-06-24 14:26:53.508] [Dispatcher] /home/www-data/.rvm/gems/ruby-2.2.1/bundler/gems/websocket-rails-1b81a919731b/lib/websocket_rails/internal_events.rb:20:in `subscribe_to_channel'
E [2015-06-24 14:26:53.508] [Dispatcher] /home/www-data/.rvm/gems/ruby-2.2.1/bundler/gems/websocket-rails-1b81a919731b/lib/websocket_rails/base_controller.rb:27:in `process_action'
E [2015-06-24 14:26:53.508] [Dispatcher] /home/www-data/.rvm/gems/ruby-2.2.1/gems/actionpack-4.2.1/lib/abstract_controller/callbacks.rb:20:in `block in process_action'
E [2015-06-24 14:26:53.508] [Dispatcher] /home/www-data/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.1/lib/active_support/callbacks.rb:88:in `call'
E [2015-06-24 14:26:53.508] [Dispatcher] /home/www-data/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.1/lib/active_support/callbacks.rb:88:in `_run_callbacks'
E [2015-06-24 14:26:53.508] [Dispatcher] /home/www-data/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.1/lib/active_support/callbacks.rb:776:in `_run_process_action_callbacks'
E [2015-06-24 14:26:53.508] [Dispatcher] /home/www-data/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.1/lib/active_support/callbacks.rb:81:in `run_callbacks'
E [2015-06-24 14:26:53.508] [Dispatcher] /home/www-data/.rvm/gems/ruby-2.2.1/gems/actionpack-4.2.1/lib/abstract_controller/callbacks.rb:19:in `process_action'
E [2015-06-24 14:26:53.508] [Dispatcher] /home/www-data/.rvm/gems/ruby-2.2.1/bundler/gems/websocket-rails-1b81a919731b/lib/websocket_rails/dispatcher.rb:67:in `block (3 levels) in route'
E [2015-06-24 14:26:53.508] [Dispatcher] /home/www-data/.rvm/gems/ruby-2.2.1/bundler/gems/websocket-rails-1b81a919731b/lib/websocket_rails/logging.rb:66:in `call'
E [2015-06-24 14:26:53.508] [Dispatcher] /home/www-data/.rvm/gems/ruby-2.2.1/bundler/gems/websocket-rails-1b81a919731b/lib/websocket_rails/logging.rb:66:in `log_event'
E [2015-06-24 14:26:53.508] [Dispatcher] /home/www-data/.rvm/gems/ruby-2.2.1/bundler/gems/websocket-rails-1b81a919731b/lib/websocket_rails/dispatcher.rb:64:in `block (2 levels) in route'

#websocket_rails_server.log 
Exiting!
/home/www-data/.rvm/gems/ruby-2.2.1/gems/connection_pool-2.2.0/lib/connection_pool/timed_stack.rb:85:in `block (2 levels) in pop': Waited 5 sec (Timeout::Error)
	from /home/www-data/.rvm/gems/ruby-2.2.1/gems/connection_pool-2.2.0/lib/connection_pool/timed_stack.rb:77:in `loop'
	from /home/www-data/.rvm/gems/ruby-2.2.1/gems/connection_pool-2.2.0/lib/connection_pool/timed_stack.rb:77:in `block in pop'
	from /home/www-data/.rvm/gems/ruby-2.2.1/gems/connection_pool-2.2.0/lib/connection_pool/timed_stack.rb:76:in `synchronize'
	from /home/www-data/.rvm/gems/ruby-2.2.1/gems/connection_pool-2.2.0/lib/connection_pool/timed_stack.rb:76:in `pop'
	from /home/www-data/.rvm/gems/ruby-2.2.1/gems/connection_pool-2.2.0/lib/connection_pool.rb:89:in `checkout'
	from /home/www-data/.rvm/gems/ruby-2.2.1/gems/connection_pool-2.2.0/lib/connection_pool.rb:61:in `block in with'
	from /home/www-data/.rvm/gems/ruby-2.2.1/gems/connection_pool-2.2.0/lib/connection_pool.rb:60:in `handle_interrupt'
	from /home/www-data/.rvm/gems/ruby-2.2.1/gems/connection_pool-2.2.0/lib/connection_pool.rb:60:in `with'
	from /home/www-data/.rvm/gems/ruby-2.2.1/gems/connection_pool-2.2.0/lib/connection_pool.rb:131:in `with'
	from /home/www-data/.rvm/gems/ruby-2.2.1/gems/connection_pool-2.2.0/lib/connection_pool.rb:143:in `method_missing'
	from /home/www-data/.rvm/gems/ruby-2.2.1/gems/redis-objects-1.2.0/lib/redis/list.rb:104:in `delete'
	from /home/www-data/.rvm/gems/ruby-2.2.1/bundler/gems/websocket-rails-1b81a919731b/lib/websocket_rails/synchronization.rb:163:in `remove_server'
	from /home/www-data/.rvm/gems/ruby-2.2.1/bundler/gems/websocket-rails-1b81a919731b/lib/websocket_rails/synchronization.rb:144:in `shutdown!'
	from /home/www-data/.rvm/gems/ruby-2.2.1/bundler/gems/websocket-rails-1b81a919731b/lib/websocket_rails/synchronization.rb:35:in `shutdown!'
	from /home/www-data/.rvm/gems/ruby-2.2.1/bundler/gems/websocket-rails-1b81a919731b/lib/websocket_rails/connection_manager.rb:42:in `block (3 levels) in initialize'
	from /home/www-data/.rvm/gems/ruby-2.2.1/gems/eventmachine-1.0.7/lib/eventmachine.rb:190:in `call'
	from /home/www-data/.rvm/gems/ruby-2.2.1/gems/eventmachine-1.0.7/lib/eventmachine.rb:190:in `ensure in run'
	from /home/www-data/.rvm/gems/ruby-2.2.1/gems/eventmachine-1.0.7/lib/eventmachine.rb:218:in `run'
	from /home/www-data/.rvm/gems/ruby-2.2.1/gems/thin-1.6.3/lib/thin/backends/base.rb:73:in `start'
	from /home/www-data/.rvm/gems/ruby-2.2.1/gems/thin-1.6.3/lib/thin/server.rb:162:in `start'
	from /home/www-data/.rvm/gems/ruby-2.2.1/gems/thin-1.6.3/lib/thin/controllers/controller.rb:87:in `start'
	from /home/www-data/.rvm/gems/ruby-2.2.1/bundler/gems/websocket-rails-1b81a919731b/lib/rails/tasks/websocket_rails.tasks:14:in `block (3 levels) in <top (required)>'
	from /home/www-data/.rvm/gems/ruby-2.2.1/bundler/gems/websocket-rails-1b81a919731b/lib/rails/tasks/websocket_rails.tasks:13:in `fork'
	from /home/www-data/.rvm/gems/ruby-2.2.1/bundler/gems/websocket-rails-1b81a919731b/lib/rails/tasks/websocket_rails.tasks:13:in `block (2 levels) in <top (required)>'
	from /home/www-data/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/rake/task.rb:240:in `call'
	from /home/www-data/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/rake/task.rb:240:in `block in execute'
	from /home/www-data/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/rake/task.rb:235:in `each'
	from /home/www-data/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/rake/task.rb:235:in `execute'
	from /home/www-data/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/rake/task.rb:179:in `block in invoke_with_call_chain'
	from /home/www-data/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/monitor.rb:211:in `mon_synchronize'
	from /home/www-data/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/rake/task.rb:172:in `invoke_with_call_chain'
	from /home/www-data/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/rake/task.rb:165:in `invoke'
	from /home/www-data/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/rake/application.rb:150:in `invoke_task'
	from /home/www-data/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/rake/application.rb:106:in `block (2 levels) in top_level'
	from /home/www-data/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/rake/application.rb:106:in `each'
	from /home/www-data/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/rake/application.rb:106:in `block in top_level'
	from /home/www-data/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/rake/application.rb:115:in `run_with_threads'
	from /home/www-data/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/rake/application.rb:100:in `top_level'
	from /home/www-data/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/rake/application.rb:78:in `block in run'
	from /home/www-data/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/rake/application.rb:176:in `standard_exception_handling'
	from /home/www-data/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/rake/application.rb:75:in `run'
	from /home/www-data/.rvm/rubies/ruby-2.2.1/bin/rake:33:in `<main>'

**Comment by phlegx** [comment]
Try out gem ```gem 'websocket-rails', github: 'moaa/websocket-rails', branch: 'sync_fixes'```. Remove first all gems and re-bundle. After that start Redis console ```redis-cli``` and flush all.

**Comment by langesi** [comment]
I've had the same problem. gem 'websocket-rails', github: 'moaa/websocket-rails', branch: 'sync_fixes' fixed it.
Thanks!

**Comment by ashishsingla89** [comment]
Hi @moaa, I am using 'threadsocket-rails' branch. I am using RedisCloud service of heroku with memory size 30MB.(link:  https://elements.heroku.com/addons/rediscloud)

In my config, I have enable channel synchronization and set redis_options as:

config.redis_options = { :host => APP_CONFIG['REDIS_CLOUD_HOST'],
                            :port => APP_CONFIG['REDIS_CLOUD_PORT'],
                            :password => APP_CONFIG['REDIS_CLOUD_PASSWORD']}

When android or ios devices trigger the event, they get this empty hash (when I use redis):

["add_to_channel",{},{"id":null,"channel":null,"user_id":null,"success":false,"result":null,"token":null,"server_token":null}]

I also get this error: NameError Exception: undefined local variable or method `sync' for #<WebsocketRails::UserManager::LocalConnection:0x007fe271873c18>

Otherwise they get correct response("message":"user join new channel"):

["add_to_channel",{"message":"user join new channel"},{"id":null,"channel":null,"user_id":null,"success":false,"result":null,"token":null,"server_token":null}]

I use this code to send an event to a specific client:
WebsocketRails.users[recipient_id].send_message('add_to_channel', {:message => message[:body]})

**Comment by rwu1997** [comment]
@ashishsingla89 Did you manage to fix the sync issue?

**Comment by jstdoit** [comment]
Bump. 3.2.0 Fixes a similar issue.
