### ISSUE TITLE
sending messages from normal controller fails

### ISSUE THREAD

**Issue by pschrammel** [websocket-rails/websocket-rails#325]
Hi,
I'm experimenting wit websocket-rails and stumbeled over a strange problem. My setup:
Two rails processes with thin on different ports.   My config is

`
config.standalone = false
config.synchronize = true
config.redis_options = {
:host => 'localhost',
:port => '6379'}
`
Everythign seems to work fine, I can send recive messages on the different ports, I can even send messages to the channels from the rails console. But if I want to send to a publi channel from a usual rails controller :
`WebsocketRails[:all_chat].trigger(:chat_msg,
                                      {:txt => 'hallo', :user_name => :system})
`
I get the following error:

`
Exiting

/home/vagrant/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/redis-3.2.1/lib/redis/client.rb:331:in 'rescue in establish_connection': Error connecting to Redis on localhost:6379 (Errno::ECONNREFUSED) (Redis::CannotConnectError)
	from /home/vagrant/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/redis-3.2.1/lib/redis/client.rb:317:in 'establish_connection'
	from /home/vagrant/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/redis-3.2.1/lib/redis/client.rb:94:in 'block in connect'
	from /home/vagrant/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/redis-3.2.1/lib/redis/client.rb:279:in 'with_reconnect'
	from /home/vagrant/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/redis-3.2.1/lib/redis/client.rb:93:in 'connect'
	from /home/vagrant/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/redis-3.2.1/lib/redis/client.rb:350:in 'ensure_connected'
	from /home/vagrant/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/redis-3.2.1/lib/redis/client.rb:207:in 'block in process'
	from /home/vagrant/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/redis-3.2.1/lib/redis/client.rb:292:in 'logging'
	from /home/vagrant/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/redis-3.2.1/lib/redis/client.rb:206:in 'process'
	from /home/vagrant/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/redis-3.2.1/lib/redis/client.rb:112:in 'call'
	from /home/vagrant/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/redis-3.2.1/lib/redis.rb:2022:in 'block in publish'
	from /home/vagrant/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/redis-3.2.1/lib/redis.rb:37:in 'block in synchronize'
	from /home/vagrant/.rbenv/versions/2.1.5/lib/ruby/2.1.0/monitor.rb:211:in 'mon_synchronize'
	from /home/vagrant/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/redis-3.2.1/lib/redis.rb:37:in 'synchronize'
	from /home/vagrant/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/redis-3.2.1/lib/redis.rb:2021:in 'publish'
	from /home/vagrant/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/bundler/gems/websocket-rails-712fd4e35325/lib/websocket_rails/synchronization.rb:63:in 'block in publish'
vagrant@fixingthenet:/vagrant/apps/fixingthenet-root$ 
`

The redis server is there (I can chat on different processes). Thx for your help

**Comment by busiq** [comment]
I have the same issue, any ideas guys? I figured that if 2 clients are connected to the server, everything works fine, then if I connect another one and try to send any message - server crashes. I tried both standard and standalone options.

**Comment by moaa** [comment]
I have implemented some fixes for this.  Can you try updating your gemfile to:

```ruby
gem 'websocket-rails', github: 'moaa/websocket-rails', branch: 'sync_fixes'
```
I'll merge these fixes into master as long as I get positive feedback from everyone.

**Comment by sslotsky** [comment]
@moaa I am experiencing this error in production but not in development. Given that this is the case, would you expect that switching to this branch would be of any help to me?

**Comment by phlegx** [comment]
@moaa @pschrammel I get the same problem on an app. I have created a small test app that works. Here the data:

* in ```application.rb```: ```config.middleware.delete Rack::Lock```
* websocket-rails config:   ```config.standalone = false````and ```config.synchronize = true```
* Ruby Version 2.2.2
* Rails Version 4.1.7
* Redis Version: 2.8.4
* Em-synchrony 1.0.4
* Eventmachine 1.0.7
* Faye-websocket 0.9.2
* Hiredis 0.6.0
* Redis 3.2.1
* Redis-objects 1.2.0
* Thin 1.6.3
* Websocket-driver 0.5.4
* Websocket-extensions 0.1.2

I continue to test, because I need to get run my app that has the same error reported in this issue. I will report. Using the latest release 0.7.0 I get this errors on channel tokens: https://github.com/websocket-rails/websocket-rails/issues/349 and https://github.com/websocket-rails/websocket-rails/issues/350. This version (sync_fixes) of @moaa seams to work in a fresh app.

**Comment by phlegx** [comment]
# Report 1

Uninstalling all gems with ```gem uninstall --all``` and deleting ```Gemfile.lock``` helps to remove all. After ```bundle``` all required gems are installed with the version listed in the above comment. Now the app seams to work. I continue to test.

**Comment by phlegx** [comment]
## Report 2

The websocket-rails crashs if I use this client https://github.com/phlegx/websocket-rails-client-cpp. This websocket client works without problems on 0.7.0 with ```config.synchronize = true```. Any idea?

```log
/home/linux/.rvm/gems/ruby-2.1.4@my_app/gems/em-synchrony-1.0.4/lib/em-synchrony.rb:75:in `yield': can't yield from root fiber (FiberError)
        from /home/linux/.rvm/gems/ruby-2.1.4@my_app/gems/em-synchrony-1.0.4/lib/em-synchrony.rb:75:in `sync'
        from /home/linux/.rvm/gems/ruby-2.1.4@my_app/gems/redis-3.2.1/lib/redis/connection/synchrony.rb:47:in `read'
        from /home/linux/.rvm/gems/ruby-2.1.4@my_app/gems/redis-3.2.1/lib/redis/connection/synchrony.rb:110:in `read'
        from /home/linux/.rvm/gems/ruby-2.1.4@my_app/gems/redis-3.2.1/lib/redis/client.rb:248:in `block in read'
        from /home/linux/.rvm/gems/ruby-2.1.4@my_app/gems/redis-3.2.1/lib/redis/client.rb:236:in `io'
        from /home/linux/.rvm/gems/ruby-2.1.4@my_app/gems/redis-3.2.1/lib/redis/client.rb:247:in `read'
        from /home/linux/.rvm/gems/ruby-2.1.4@my_app/gems/redis-3.2.1/lib/redis/client.rb:112:in `block in call'
        from /home/linux/.rvm/gems/ruby-2.1.4@my_app/gems/redis-3.2.1/lib/redis/client.rb:217:in `block (2 levels) in process'
        from /home/linux/.rvm/gems/ruby-2.1.4@my_app/gems/redis-3.2.1/lib/redis/client.rb:353:in `ensure_connected'
        from /home/linux/.rvm/gems/ruby-2.1.4@my_app/gems/redis-3.2.1/lib/redis/client.rb:207:in `block in process'
        from /home/linux/.rvm/gems/ruby-2.1.4@my_app/gems/redis-3.2.1/lib/redis/client.rb:292:in `logging'
        from /home/linux/.rvm/gems/ruby-2.1.4@my_app/gems/redis-3.2.1/lib/redis/client.rb:206:in `process'
        from /home/linux/.rvm/gems/ruby-2.1.4@my_app/gems/redis-3.2.1/lib/redis/client.rb:112:in `call'
        from /home/linux/.rvm/gems/ruby-2.1.4@my_app/gems/redis-3.2.1/lib/redis.rb:1184:in `block in lrem'
        from /home/linux/.rvm/gems/ruby-2.1.4@my_app/gems/redis-3.2.1/lib/redis.rb:37:in `block in synchronize'
        from /home/linux/.rvm/rubies/ruby-2.1.4/lib/ruby/2.1.0/monitor.rb:211:in `mon_synchronize'
        from /home/linux/.rvm/gems/ruby-2.1.4@my_app/gems/redis-3.2.1/lib/redis.rb:37:in `synchronize'
        from /home/linux/.rvm/gems/ruby-2.1.4@my_app/gems/redis-3.2.1/lib/redis.rb:1183:in `lrem'
        from /home/linux/.rvm/gems/ruby-2.1.4@my_app/gems/connection_pool-2.2.0/lib/connection_pool.rb:144:in `block in method_missing'
        from /home/linux/.rvm/gems/ruby-2.1.4@my_app/gems/connection_pool-2.2.0/lib/connection_pool.rb:64:in `block (2 levels) in with'
        from /home/linux/.rvm/gems/ruby-2.1.4@my_app/gems/connection_pool-2.2.0/lib/connection_pool.rb:63:in `handle_interrupt'
        from /home/linux/.rvm/gems/ruby-2.1.4@my_app/gems/connection_pool-2.2.0/lib/connection_pool.rb:63:in `block in with'
        from /home/linux/.rvm/gems/ruby-2.1.4@my_app/gems/connection_pool-2.2.0/lib/connection_pool.rb:60:in `handle_interrupt'
        from /home/linux/.rvm/gems/ruby-2.1.4@my_app/gems/connection_pool-2.2.0/lib/connection_pool.rb:60:in `with'
        from /home/linux/.rvm/gems/ruby-2.1.4@my_app/gems/connection_pool-2.2.0/lib/connection_pool.rb:131:in `with'
        from /home/linux/.rvm/gems/ruby-2.1.4@my_app/gems/connection_pool-2.2.0/lib/connection_pool.rb:143:in `method_missing'
        from /home/linux/.rvm/gems/ruby-2.1.4@my_app/gems/redis-objects-1.2.0/lib/redis/list.rb:104:in `delete'
        from /home/linux/my_app/vendor/gems/websocket-rails/lib/websocket_rails/synchronization.rb:163:in `remove_server'
        from /home/linux/my_app/vendor/gems/websocket-rails/lib/websocket_rails/synchronization.rb:144:in `shutdown!'
        from /home/linux/my_app/vendor/gems/websocket-rails/lib/websocket_rails/synchronization.rb:35:in `shutdown!'
        from /home/linux/my_app/vendor/gems/websocket-rails/lib/websocket_rails/connection_manager.rb:42:in `block (3 levels) in initialize'
        from /home/linux/.rvm/gems/ruby-2.1.4@my_app/gems/eventmachine-1.0.7/lib/eventmachine.rb:190:in `call'
        from /home/linux/.rvm/gems/ruby-2.1.4@my_app/gems/eventmachine-1.0.7/lib/eventmachine.rb:190:in `ensure in run'
        from /home/linux/.rvm/gems/ruby-2.1.4@my_app/gems/eventmachine-1.0.7/lib/eventmachine.rb:218:in `run'
        from /home/linux/.rvm/gems/ruby-2.1.4@my_app/gems/thin-1.6.3/lib/thin/backends/base.rb:73:in `start'
        from /home/linux/.rvm/gems/ruby-2.1.4@my_app/gems/thin-1.6.3/lib/thin/server.rb:162:in `start'
        from /home/linux/.rvm/gems/ruby-2.1.4@my_app/gems/rack-1.5.5/lib/rack/handler/thin.rb:16:in `run'
        from /home/linux/.rvm/gems/ruby-2.1.4@my_app/gems/rack-1.5.5/lib/rack/server.rb:264:in `start'
        from /home/linux/.rvm/gems/ruby-2.1.4@my_app/gems/railties-4.1.7/lib/rails/commands/server.rb:69:in `start'
        from /home/linux/.rvm/gems/ruby-2.1.4@my_app/gems/railties-4.1.7/lib/rails/commands/commands_tasks.rb:81:in `block in server'
        from /home/linux/.rvm/gems/ruby-2.1.4@my_app/gems/railties-4.1.7/lib/rails/commands/commands_tasks.rb:76:in `tap'
        from /home/linux/.rvm/gems/ruby-2.1.4@my_app/gems/railties-4.1.7/lib/rails/commands/commands_tasks.rb:76:in `server'
        from /home/linux/.rvm/gems/ruby-2.1.4@my_app/gems/railties-4.1.7/lib/rails/commands/commands_tasks.rb:40:in `run_command!'
        from /home/linux/.rvm/gems/ruby-2.1.4@my_app/gems/railties-4.1.7/lib/rails/commands.rb:17:in `<top (required)>'
        from bin/rails:4:in `require'
        from bin/rails:4:in `<main>'
```

**Comment by phlegx** [comment]
@moaa I have a question to your branch ```sync_fix```.

I have the following process flow:

* Js client triggers an event ```my_namespace.test```.
* In function ```test``` (```MyNamespaceController <  < WebsocketRails::BaseController```) I call ```connection.register_user``` (own implementation in websocket-rails).
* I require this function to register a user after websocket client has connected.
* I have add the code to websocket-rails for ```connection.register_user```:

```ruby
# websocket_rails/connection_adapter.rb

def register_user
   dispatcher.connection_manager.register_user self
end

# websocket_rails/connection_manager.rb

def register_user(connection)
  register_user_connection connection
end
```

This call to ```connection.register_user``` causes the server crash with ```/home/phlegx/.rvm/gems/ruby-2.1.4@luianta-manager/gems/em-synchrony-1.0.4/lib/em-synchrony.rb:75:in `yield': can't yield from root fiber (FiberError)```. Can you please help me. Am desperate!

I have tried to add ```Fiber.new do ... end.resume``` to  ```connection.register_user``` but I get the same error.

**Comment by phlegx** [comment]
## Report 2

Server are not synchronized with redis. Doing ```HGETALL 'websocket_rails.servers'``` on ```redis-cli``` I get ```(empty list or set)```.

**Comment by zaynyatyi** [comment]
@moaa gem 'websocket-rails', github: 'moaa/websocket-rails', branch: 'sync_fixes' worked for me

my websocket setup was: config.standalone = true config.synchronize = false
was experiencing bug when user reconnects to the websocket on page reloading

**Comment by nanamkim** [comment]
@moaa gem 'websocket-rails', github: 'moaa/websocket-rails', branch: 'sync_fixes' worked for me

**Comment by shisongsong** [comment]
@zaynyatyi Hi, what's the next?
