### ISSUE TITLE
Running rails g websocket_rails:install gives syntax errors

### ISSUE THREAD

**Issue by swatisinghi** [websocket-rails/websocket-rails#327]
Faraday: you may want to install system_timer for reliable timeouts
/usr/local/rvm/gems/ruby-1.8.7-p374/gems/activesupport-3.2.17/lib/active_support/dependencies.rb:251:in `require': /usr/local/rvm/gems/ruby-1.8.7-p374/gems/websocket-rails-0.7.0/lib/websocket_rails/synchronization.rb:154: syntax error, unexpected ':', expecting ')' (SyntaxError)
...users', id, user.as_json(root: false).to_json
                              ^
/usr/local/rvm/gems/ruby-1.8.7-p374/gems/websocket-rails-0.7.0/lib/websocket_rails/synchronization.rb:159: syntax error, unexpected kDO_BLOCK, expecting kEND
/usr/local/rvm/gems/ruby-1.8.7-p374/gems/websocket-rails-0.7.0/lib/websocket_rails/synchronization.rb:165: syntax error, unexpected kDO_BLOCK, expecting kEND
/usr/local/rvm/gems/ruby-1.8.7-p374/gems/websocket-rails-0.7.0/lib/websocket_rails/synchronization.rb:172: syntax error, unexpected kDO_BLOCK, expecting kEND
/usr/local/rvm/gems/ruby-1.8.7-p374/gems/websocket-rails-0.7.0/lib/websocket_rails/synchronization.rb:175: syntax error, unexpected kEND, expecting $end
	from /usr/local/rvm/gems/ruby-1.8.7-p374/gems/activesupport-3.2.17/lib/active_support/dependencies.rb:251:in `require'
	from /usr/local/rvm/gems/ruby-1.8.7-p374/gems/activesupport-3.2.17/lib/active_support/dependencies.rb:236:in `load_dependency'
	from /usr/local/rvm/gems/ruby-1.8.7-p374/gems/activesupport-3.2.17/lib/active_support/dependencies.rb:251:in `require'
	from /usr/local/rvm/gems/ruby-1.8.7-p374/gems/websocket-rails-0.7.0/lib/websocket-rails.rb:35
	from /usr/local/rvm/gems/ruby-1.8.7-p374/gems/bundler-1.7.11/lib/bundler/runtime.rb:76:in `require'
	from /usr/local/rvm/gems/ruby-1.8.7-p374/gems/bundler-1.7.11/lib/bundler/runtime.rb:76:in `require'
	from /usr/local/rvm/gems/ruby-1.8.7-p374/gems/bundler-1.7.11/lib/bundler/runtime.rb:72:in `each'
	from /usr/local/rvm/gems/ruby-1.8.7-p374/gems/bundler-1.7.11/lib/bundler/runtime.rb:72:in `require'
	from /usr/local/rvm/gems/ruby-1.8.7-p374/gems/bundler-1.7.11/lib/bundler/runtime.rb:61:in `each'
	from /usr/local/rvm/gems/ruby-1.8.7-p374/gems/bundler-1.7.11/lib/bundler/runtime.rb:61:in `require'
	from /usr/local/rvm/gems/ruby-1.8.7-p374/gems/bundler-1.7.11/lib/bundler.rb:134:in `require'
	from /home/swati/src/qbol/tapp/config/application.rb:8
	from /usr/local/rvm/gems/ruby-1.8.7-p374/gems/railties-3.2.17/lib/rails/commands.rb:24:in `require'
	from /usr/local/rvm/gems/ruby-1.8.7-p374/gems/railties-3.2.17/lib/rails/commands.rb:24
	from script/rails:6:in `require'
	from script/rails:6

What version of rails is needed?

**Comment by deepsystm** [comment]
I think rails 4.0+
and ruby 1.9.3+
