### ISSUE TITLE
Websockets causing a Redis ECONNREFUSED error

### ISSUE THREAD

**Issue by gavinheale** [websocket-rails/websocket-rails#330]
I am getting a curious connection refused error from Redis that causes the server to fail.

```
/Users/gavin/.rvm/gems/ruby-2.2.1@kugadi/gems/redis-3.2.1/lib/redis/client.rb:331:in `rescue in establish_connection': Error connecting to Redis on 127.0.0.1:6379 (Errno::ECONNREFUSED) (Redis::CannotConnectError)
Exiting
	from /Users/gavin/.rvm/gems/ruby-2.2.1@kugadi/gems/redis-3.2.1/lib/redis/client.rb:317:in `establish_connection'
	from /Users/gavin/.rvm/gems/ruby-2.2.1@kugadi/gems/redis-3.2.1/lib/redis/client.rb:94:in `block in connect'
	from /Users/gavin/.rvm/gems/ruby-2.2.1@kugadi/gems/redis-3.2.1/lib/redis/client.rb:279:in `with_reconnect'
	from /Users/gavin/.rvm/gems/ruby-2.2.1@kugadi/gems/redis-3.2.1/lib/redis/client.rb:93:in `connect'
	from /Users/gavin/.rvm/gems/ruby-2.2.1@kugadi/gems/redis-3.2.1/lib/redis/client.rb:350:in `ensure_connected'
	from /Users/gavin/.rvm/gems/ruby-2.2.1@kugadi/gems/redis-3.2.1/lib/redis/client.rb:207:in `block in process'
	from /Users/gavin/.rvm/gems/ruby-2.2.1@kugadi/gems/redis-3.2.1/lib/redis/client.rb:292:in `logging'
	from /Users/gavin/.rvm/gems/ruby-2.2.1@kugadi/gems/redis-3.2.1/lib/redis/client.rb:206:in `process'
	from /Users/gavin/.rvm/gems/ruby-2.2.1@kugadi/gems/redis-3.2.1/lib/redis/client.rb:112:in `call'
	from /Users/gavin/.rvm/gems/ruby-2.2.1@kugadi/gems/redis-3.2.1/lib/redis.rb:1901:in `block in hget'
	from /Users/gavin/.rvm/gems/ruby-2.2.1@kugadi/gems/redis-3.2.1/lib/redis.rb:37:in `block in synchronize'
	from /Users/gavin/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/monitor.rb:211:in `mon_synchronize'
	from /Users/gavin/.rvm/gems/ruby-2.2.1@kugadi/gems/redis-3.2.1/lib/redis.rb:37:in `synchronize'
	from /Users/gavin/.rvm/gems/ruby-2.2.1@kugadi/gems/redis-3.2.1/lib/redis.rb:1900:in `hget'
	from /Users/gavin/.rvm/gems/ruby-2.2.1@kugadi/gems/redis-objects-1.1.0/lib/redis/hash_key.rb:27:in `hget'
	from /Users/gavin/.rvm/gems/ruby-2.2.1@kugadi/gems/websocket-rails-0.7.0/lib/websocket_rails/channel.rb:58:in `token'
	from /Users/gavin/.rvm/gems/ruby-2.2.1@kugadi/gems/websocket-rails-0.7.0/lib/websocket_rails/channel.rb:31:in `trigger'
	from /Users/gavin/RubymineProjects/overton/app/models/geographic_fix.rb:15:in `block in send_to_websocket'

Process finished with exit code 1

```

I have put Redis in debug mode and I can see the connections.  I have redis-cli running in monitor mode which is one connection.  I then get 2 new ones for the stand alone server and some more for the main server.  Here is an extract from the redis log.

```
82377:M 27 Apr 13:15:58.618 - Accepted 127.0.0.1:56393
82377:M 27 Apr 13:16:02.562 - DB 0: 3 keys (0 volatile) in 4 slots HT.
82377:M 27 Apr 13:16:02.563 - 1 clients connected (0 slaves), 977856 bytes in use
82377:M 27 Apr 13:16:11.106 - DB 0: 3 keys (0 volatile) in 4 slots HT.
82377:M 27 Apr 13:16:11.107 - 1 clients connected (0 slaves), 977856 bytes in use
82377:M 27 Apr 13:16:19.695 - DB 0: 3 keys (0 volatile) in 4 slots HT.
82377:M 27 Apr 13:16:19.696 - 1 clients connected (0 slaves), 977856 bytes in use
82377:M 27 Apr 13:16:28.297 - DB 0: 3 keys (0 volatile) in 4 slots HT.
82377:M 27 Apr 13:16:28.297 - 1 clients connected (0 slaves), 977856 bytes in use
82377:M 27 Apr 13:16:36.820 - DB 0: 3 keys (0 volatile) in 4 slots HT.
82377:M 27 Apr 13:16:36.820 - 1 clients connected (0 slaves), 977856 bytes in use
82377:M 27 Apr 13:16:45.455 - DB 0: 3 keys (0 volatile) in 4 slots HT.
82377:M 27 Apr 13:16:45.455 - 1 clients connected (0 slaves), 977856 bytes in use
82377:M 27 Apr 13:16:46.848 - Accepted 127.0.0.1:56395
82377:M 27 Apr 13:16:46.874 - Accepted 127.0.0.1:56396
82377:M 27 Apr 13:16:53.891 - DB 0: 3 keys (0 volatile) in 4 slots HT.
82377:M 27 Apr 13:16:53.891 - 3 clients connected (0 slaves), 1012832 bytes in use
82377:M 27 Apr 13:17:02.504 - DB 0: 3 keys (0 volatile) in 4 slots HT.
82377:M 27 Apr 13:17:02.504 - 3 clients connected (0 slaves), 1012832 bytes in use
82377:M 27 Apr 13:17:11.100 - DB 0: 3 keys (0 volatile) in 4 slots HT.
82377:M 27 Apr 13:17:11.100 - 3 clients connected (0 slaves), 1012832 bytes in use
82377:M 27 Apr 13:17:13.846 - Accepted 127.0.0.1:56397
82377:M 27 Apr 13:17:13.847 - Accepted 127.0.0.1:56398
82377:M 27 Apr 13:17:19.651 - DB 0: 3 keys (0 volatile) in 4 slots HT.
82377:M 27 Apr 13:17:19.651 - 5 clients connected (0 slaves), 1047728 bytes in use
82377:M 27 Apr 13:17:28.254 - DB 0: 3 keys (0 volatile) in 4 slots HT.
82377:M 27 Apr 13:17:28.254 - 5 clients connected (0 slaves), 1047728 bytes in use
82377:M 27 Apr 13:17:36.871 - DB 0: 3 keys (0 volatile) in 4 slots HT.
82377:M 27 Apr 13:17:36.871 - 5 clients connected (0 slaves), 1047728 bytes in use
82377:M 27 Apr 13:17:45.502 - DB 0: 3 keys (0 volatile) in 4 slots HT.
82377:M 27 Apr 13:17:45.502 - 5 clients connected (0 slaves), 1047728 bytes in use
82377:M 27 Apr 13:17:53.004 - Accepted 127.0.0.1:56401
82377:M 27 Apr 13:17:53.104 - Client closed connection
82377:M 27 Apr 13:17:53.128 - Accepted 127.0.0.1:56402
82377:M 27 Apr 13:17:53.172 - Client closed connection
82377:M 27 Apr 13:17:53.172 - Accepted 127.0.0.1:56403
82377:M 27 Apr 13:17:53.173 - Client closed connection
82377:M 27 Apr 13:17:53.173 - Client closed connection
82377:M 27 Apr 13:17:53.173 - Accepted 127.0.0.1:56404
82377:M 27 Apr 13:17:53.193 - Client closed connection
82377:M 27 Apr 13:17:53.255 - Client closed connection
82377:M 27 Apr 13:17:53.936 - DB 0: 3 keys (0 volatile) in 4 slots HT.
82377:M 27 Apr 13:17:53.936 - 3 clients connected (0 slaves), 1012832 bytes in use
82377:M 27 Apr 13:18:02.399 - DB 0: 3 keys (0 volatile) in 4 slots HT.
82377:M 27 Apr 13:18:02.399 - 3 clients connected (0 slaves), 1012832 bytes in use
```

Here is the Redis monitor ouput
```
Gavins-MBP:~ gavin$ redis-cli monitor
OK
1430155006.874010 [0 127.0.0.1:56395] "sismember" "websocket_rails.active_servers" "0EEXNlgIKgLkvJ2zNearKw"
1430155006.874465 [0 127.0.0.1:56395] "sadd" "websocket_rails.active_servers" "0EEXNlgIKgLkvJ2zNearKw"
1430155006.895314 [0 127.0.0.1:56396] "subscribe" "websocket_rails.events"
1430155033.846412 [0 127.0.0.1:56397] "sismember" "websocket_rails.active_servers" "MLVoGmT94bm2_smOSk56LQ"
1430155033.846744 [0 127.0.0.1:56397] "sadd" "websocket_rails.active_servers" "MLVoGmT94bm2_smOSk56LQ"
1430155033.847751 [0 127.0.0.1:56398] "subscribe" "websocket_rails.events"
1430155073.171663 [0 127.0.0.1:56402] "srem" "websocket_rails.active_servers" "MLVoGmT94bm2_smOSk56LQ"
^C
Gavins-MBP:~ gavin$ 

```

My configuration is 
```ruby
WebsocketRails.setup do |config|

  # Uncomment to override the default log level. The log level can be
  # any of the standard Logger log levels. By default it will mirror the
  # current Rails environment log level.
  # config.log_level = :debug

  # Uncomment to change the default log file path.
  # config.log_path = "#{Rails.root}/log/websocket_rails.log"

  # Set to true if you wish to log the internal websocket_rails events
  # such as the keepalive `websocket_rails.ping` event.
  # config.log_internal_events = false

  # Change to true to enable standalone server mode
  # Start the standalone server with rake websocket_rails:start_server
  # * Requires Redis
  config.standalone = true

  # Change to true to enable channel synchronization between
  # multiple server instances.
  # * Requires Redis.
  config.synchronize = false

  # Uncomment and edit to point to a different redis instance.
  # Will not be used unless standalone or synchronization mode
  # is enabled.
  # config.redis_options = {:host => 'localhost', :port => '6379'}
  # config.redis_options = { driver: :ruby }

  # By default, all subscribers in to a channel will be removed
  # when that channel is made private. If you don't wish active
  # subscribers to be removed from a previously public channel
  # when making it private, set the following to true.
  # config.keep_subscribers_when_private = false

  # Used as the key for the WebsocketRails.users Hash. This method
  # will be called on the `current_user` object in your controller
  # if one exists. If `current_user` does not exist or does not
  # respond to the identifier, the key will default to `connection.id`
  # config.user_identifier = :id

  # Uncomment and change this option to override the class associated
  # with your `current_user` object. This class will be used when
  # synchronization is enabled and you trigger events from background
  # jobs using the WebsocketRails.users UserManager.
  # config.user_class = User

end
```
Any idea why this might be happening?

**Comment by gavinheale** [comment]
I have changed from thin to puma and it seems to have resolved the issue.

**Comment by MhdSyrwan** [comment]
This problem happened in my case too, why don't we change the [redis fetcher method](https://github.com/websocket-rails/websocket-rails/blob/master/lib/websocket_rails/synchronization.rb#L46) to be more stable like this ?

```
    def redis
      return @redis if @redis && @redis.connected?
      begin
        redis_options = WebsocketRails.config.redis_options
        EM.reactor_running? ? Redis.new(redis_options) : ruby_redis
      end
    end
```

**Comment by rubinsh** [comment]
@MhdSyrwan - I applied your suggestion as a Monkey Patch and it seems to have improved stability.
I did not get the Redis::CannotConnectError error again (yet) :+1: 

@moaa - I don't understand why this issue was closed - switching to PUMA or to UNICORN is not a valid solution in my mind - (I want to use Thin in my production environment and I don't want to use a threaded server such as PUMA)

Thanks.

**Comment by MhdSyrwan** [comment]
@rubinsh 
Actually it improved stability, but i'm still having an exception in another case with the following stacktrace:

```
/home/mhdsyrwan/.rvm/gems/ruby-2.2.2/gems/redis-3.2.1/lib/redis/client.rb:331:in `rescue in establish_connection': Error connecting to Redis on 127.0.0.1:6379 (Errno::ECONNREFUSED) (Redis::CannotConnectError)
	from /home/mhdsyrwan/.rvm/gems/ruby-2.2.2/gems/redis-3.2.1/lib/redis/client.rb:317:in `establish_connection'
	from /home/mhdsyrwan/.rvm/gems/ruby-2.2.2/gems/redis-3.2.1/lib/redis/client.rb:94:in `block in connect'
	from /home/mhdsyrwan/.rvm/gems/ruby-2.2.2/gems/redis-3.2.1/lib/redis/client.rb:279:in `with_reconnect'
	from /home/mhdsyrwan/.rvm/gems/ruby-2.2.2/gems/redis-3.2.1/lib/redis/client.rb:93:in `connect'
	from /home/mhdsyrwan/.rvm/gems/ruby-2.2.2/gems/redis-3.2.1/lib/redis/client.rb:350:in `ensure_connected'
	from /home/mhdsyrwan/.rvm/gems/ruby-2.2.2/gems/redis-3.2.1/lib/redis/client.rb:207:in `block in process'
	from /home/mhdsyrwan/.rvm/gems/ruby-2.2.2/gems/redis-3.2.1/lib/redis/client.rb:292:in `logging'
	from /home/mhdsyrwan/.rvm/gems/ruby-2.2.2/gems/redis-3.2.1/lib/redis/client.rb:206:in `process'
	from /home/mhdsyrwan/.rvm/gems/ruby-2.2.2/gems/redis-3.2.1/lib/redis/client.rb:112:in `call'
	from /home/mhdsyrwan/.rvm/gems/ruby-2.2.2/gems/redis-3.2.1/lib/redis.rb:1901:in `block in hget'
	from /home/mhdsyrwan/.rvm/gems/ruby-2.2.2/gems/redis-3.2.1/lib/redis.rb:37:in `block in synchronize'
	from /home/mhdsyrwan/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/monitor.rb:211:in `mon_synchronize'
	from /home/mhdsyrwan/.rvm/gems/ruby-2.2.2/gems/redis-3.2.1/lib/redis.rb:37:in `synchronize'
	from /home/mhdsyrwan/.rvm/gems/ruby-2.2.2/gems/redis-3.2.1/lib/redis.rb:1900:in `hget'
	from /home/mhdsyrwan/.rvm/gems/ruby-2.2.2/gems/redis-objects-1.2.0/lib/redis/hash_key.rb:29:in `hget'
	from /home/mhdsyrwan/.rvm/gems/ruby-2.2.2/gems/websocket-rails-0.7.0/lib/websocket_rails/channel.rb:58:in `token'
	from /home/mhdsyrwan/.rvm/gems/ruby-2.2.2/gems/websocket-rails-0.7.0/lib/websocket_rails/channel.rb:31:in `trigger'
```

Since the change of server fixed the problem for @gavinheale , does it have any relation with the reloading process that's done by the development server ? (i mean it could cause some-kind of resource dropping since the redis connection object is lazy-loaded by the synchronization module)

**Comment by rubinsh** [comment]
@MhdSyrwan - I found a workaround that worked for me.
I found that I'm only having these problems when running outside of the context of my Rails app (like running a job or running from console)

When running a websockets action from a controller that inherits WebsocketRails::BaseController in the context of my Rails app - everything works.

So what I decided to do is just make sure that I always work within this context.
If I want to run a job - I just run a ruby script that uses the [websocket-client-simple gem](https://github.com/shokai/websocket-client-simple) and connects to the websockets server and sends an event.

Works like a charm for me and just works around all of these problems.

One small caveat - the format of the message should be as following:
```ruby
ws.send( '["event_name",{"data":"Example message"}]' )
```

I hope this helps you.

**Comment by rubinsh** [comment]
@MhdSyrwan - I was wrong.
What I suggested before does not solve this problem.
It worked for me because I was using boradcast_message which does not use Redis.

Will let you know if I find something that solves it.

**Comment by MhdSyrwan** [comment]
My last try is to change the `redis` driver to `synchrony` because i felt that the problem is not in the `websocket_rails` itself since the exception is cased directly by the TCP connection and it's raised by a **connected** redis client (i'm not very sure).

So, i've added the following to my gemfile:
```ruby
  gem 'redis'
  gem 'hiredis'
  gem 'em-synchrony'
```

and changed the driver as below (in `/initializers/websocket_rails.rb`):
```ruby
config.redis_options = {:host => 'localhost', :port => '6379', driver: :synchrony}
```

No exception have appeared **yet**.

**Comment by pyro2927** [comment]
@MhdSyrwan, I'm having the same issue running version 0.7.0, on Ubuntu 14.04, redis-server also being localhost.  Currently I'm seeing crashing errors once every ~12 hours with `standalone` on, and `synchronize` off.

Please report back if using synchrony helps stay connected!

**Comment by rubinsh** [comment]
@MhdSyrwan - I managed to solve the problem for me.
What I did is add the following monkey patch to the websocket_rails.rb initializer in my rails app:

```ruby
$global_redis = Redis.new

module WebsocketRails
  class Synchronization
    def redis
      @redis = $global_redis
    end

    def ruby_redis
      @ruby_redis = $global_redis
    end
  end
end
```

Not the most perfect solution but it works.
An improvement would be to add re-connection if the connection to the global redis is dropped - But I have been working with the above configuration in production for about a week and no problems so far.

My environment is:
Rails 3.2 running Thin webserver with 6 instances.
Websockets configuration is:
config.standalone = false
config.synchronize = true

**Comment by MhdSyrwan** [comment]
I've applied the same patch, it's giving a strange error with a much stranger stack trace. it sounds like a crash in the rails launcher itself !

```
/home/user/.rvm/gems/ruby-2.2.2/gems/redis-3.2.1/lib/redis/connection/synchrony.rb:81:in `yield': can't yield from root fiber (FiberError)
	from /home/user/.rvm/gems/ruby-2.2.2/gems/redis-3.2.1/lib/redis/connection/synchrony.rb:81:in `connect'
	from /home/user/.rvm/gems/ruby-2.2.2/gems/redis-3.2.1/lib/redis/client.rb:322:in `establish_connection'
	from /home/user/.rvm/gems/ruby-2.2.2/gems/redis-3.2.1/lib/redis/client.rb:94:in `block in connect'
	from /home/user/.rvm/gems/ruby-2.2.2/gems/redis-3.2.1/lib/redis/client.rb:279:in `with_reconnect'
	from /home/user/.rvm/gems/ruby-2.2.2/gems/redis-3.2.1/lib/redis/client.rb:93:in `connect'
	from /home/user/.rvm/gems/ruby-2.2.2/gems/redis-3.2.1/lib/redis/client.rb:350:in `ensure_connected'
	from /home/user/.rvm/gems/ruby-2.2.2/gems/redis-3.2.1/lib/redis/client.rb:207:in `block in process'
	from /home/user/.rvm/gems/ruby-2.2.2/gems/redis-3.2.1/lib/redis/client.rb:292:in `logging'
	from /home/user/.rvm/gems/ruby-2.2.2/gems/redis-3.2.1/lib/redis/client.rb:206:in `process'
	from /home/user/.rvm/gems/ruby-2.2.2/gems/redis-3.2.1/lib/redis/client.rb:112:in `call'
	from /home/user/.rvm/gems/ruby-2.2.2/gems/redis-3.2.1/lib/redis.rb:1254:in `block in srem'
	from /home/user/.rvm/gems/ruby-2.2.2/gems/redis-3.2.1/lib/redis.rb:37:in `block in synchronize'
	from /home/user/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/monitor.rb:211:in `mon_synchronize'
	from /home/user/.rvm/gems/ruby-2.2.2/gems/redis-3.2.1/lib/redis.rb:37:in `synchronize'
	from /home/user/.rvm/gems/ruby-2.2.2/gems/redis-3.2.1/lib/redis.rb:1253:in `srem'
	from /home/user/.rvm/gems/ruby-2.2.2/gems/websocket-rails-0.7.0/lib/websocket_rails/synchronization.rb:146:in `remove_server'
	from /home/user/.rvm/gems/ruby-2.2.2/gems/websocket-rails-0.7.0/lib/websocket_rails/synchronization.rb:127:in `shutdown!'
	from /home/user/.rvm/gems/ruby-2.2.2/gems/websocket-rails-0.7.0/lib/websocket_rails/synchronization.rb:33:in `shutdown!'
	from /home/user/.rvm/gems/ruby-2.2.2/gems/websocket-rails-0.7.0/lib/websocket_rails/connection_manager.rb:38:in `block (3 levels) in initialize'
	from /home/user/.rvm/gems/ruby-2.2.2/gems/eventmachine-1.0.8/lib/eventmachine.rb:198:in `call'
	from /home/user/.rvm/gems/ruby-2.2.2/gems/eventmachine-1.0.8/lib/eventmachine.rb:198:in `run'
	from /home/user/.rvm/gems/ruby-2.2.2/gems/thin-1.6.4/lib/thin/backends/base.rb:73:in `start'
	from /home/user/.rvm/gems/ruby-2.2.2/gems/thin-1.6.4/lib/thin/server.rb:162:in `start'
	from /home/user/.rvm/gems/ruby-2.2.2/gems/rack-1.6.0/lib/rack/handler/thin.rb:19:in `run'
	from /home/user/.rvm/gems/ruby-2.2.2/gems/rack-1.6.0/lib/rack/server.rb:286:in `start'
	from /home/user/.rvm/gems/ruby-2.2.2/gems/railties-4.2.0/lib/rails/commands/server.rb:80:in `start'
	from /home/user/.rvm/gems/ruby-2.2.2/gems/railties-4.2.0/lib/rails/commands/commands_tasks.rb:80:in `block in server'
	from /home/user/.rvm/gems/ruby-2.2.2/gems/railties-4.2.0/lib/rails/commands/commands_tasks.rb:75:in `tap'
	from /home/user/.rvm/gems/ruby-2.2.2/gems/railties-4.2.0/lib/rails/commands/commands_tasks.rb:75:in `server'
	from /home/user/.rvm/gems/ruby-2.2.2/gems/railties-4.2.0/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
	from /home/user/.rvm/gems/ruby-2.2.2/gems/railties-4.2.0/lib/rails/commands.rb:17:in `<top (required)>'
	from /home/user/projects/hotels/hilton/bin/rails:8:in `require'
	from /home/user/projects/hotels/hilton/bin/rails:8:in `<top (required)>'
	from /home/user/.rvm/gems/ruby-2.2.2/gems/spring-1.3.2/lib/spring/client/rails.rb:27:in `load'
	from /home/user/.rvm/gems/ruby-2.2.2/gems/spring-1.3.2/lib/spring/client/rails.rb:27:in `call'
	from /home/user/.rvm/gems/ruby-2.2.2/gems/spring-1.3.2/lib/spring/client/command.rb:7:in `call'
	from /home/user/.rvm/gems/ruby-2.2.2/gems/spring-1.3.2/lib/spring/client.rb:26:in `run'
	from /home/user/.rvm/gems/ruby-2.2.2/gems/spring-1.3.2/bin/spring:48:in `<top (required)>'
	from /home/user/.rvm/gems/ruby-2.2.2/gems/spring-1.3.2/lib/spring/binstub.rb:11:in `load'
	from /home/user/.rvm/gems/ruby-2.2.2/gems/spring-1.3.2/lib/spring/binstub.rb:11:in `<top (required)>'
	from /home/user/projects/hotels/hilton/bin/spring:13:in `require'
	from /home/user/projects/hotels/hilton/bin/spring:13:in `<top (required)>'
	from bin/rails:3:in `load'
	from bin/rails:3:in `<main>'
```

My environment is:
Rails 4.2 running webrick development webserver
Websockets configuration is:
config.standalone = true
config.synchronize = false # it's actually `true` because of the standalone mode

Note: when i do that using the unicorn server, the problem doesn't happen at all.

**Comment by MhdSyrwan** [comment]
@pyro2927 unfortunately i've encountered that problem using synchrony too.
So, my last result is that the reason is the development environment in my case. it could be a result of the development code reloading or something similar.

**Comment by rubinsh** [comment]
@MhdSyrwan - standalone mode with unicorn uses the Thin webserver as the websockets server.
My system used unicorn in production before, but I did not like having a separate server instance just for websockets - so I switched my server to use Thin instead of Unicorn and then I could avoid using standalone mode (websockets now just run as part of my Rails app).

I don't see the logic in using standalone = true with synchronize = false.
If synchronize = false - why do you need Redis?

I use Thin now both for development and for production - and the patch works well for me.
If you are using Rails 4.2 which is thread safe by default - you can also try using Puma as your server - as @gavinheale said it resolved these issues for him...

**Comment by MhdSyrwan** [comment]
In my project i'm forced to use unicorn, so i've chosen the standalone mode. BTW the crash is happening in the `webrick` server and not the `thin` standalone server.

Actually, it depends on the way they built the `websocket_rails` configuration, as i've seen before the configuration code overrides the value of `synchronize` in the case of `standalone` option. take a look [here](https://github.com/websocket-rails/websocket-rails/blob/712fd4e35325887956724be388821121a866c7fc/lib/websocket-rails.rb#L16)

**Comment by MhdSyrwan** [comment]
Update: I've noticed that the development server i'm using is thin (not webrick). I think the gem changed that automatically.

**Comment by dhirajbajaj** [comment]
@MhdSyrwan  Apparently i am stuck at same point; My stack is rails 4.2 + unicorn + nginx ; on production i am getting Redis Connection refused error. How did you fixed it?

_websocket_rails.rb :_ 
```
  config.standalone = true
  config.redis_options = {:host => 'localhost', :port => '6379'}
  config.synchronize = false

```

**Comment by MhdSyrwan** [comment]
It had been a long time.
What i remember is that i changed the development server to `unicorn`. since then, the issue stopped appearing.

**Comment by dhirajbajaj** [comment]
Anyone can share the production config to make it work? 
I am trying to figure it last but still getting 

> Redis::CannotConnectError: Error connecting to Redis on localhost:6379 (Errno::ECONNREFUSED)

**Comment by MhdSyrwan** [comment]
Are you sure that Redis is running ?

**Comment by dhirajbajaj** [comment]
Yes, redis is running on production as well as local env. 
Edit, I also have sidekiq running and i am using rubber for deployments etc.

```
*** [err :: ] Error connecting to Redis on 127.0.0.1:6379 (Errno::ECONNREFUSED)
*** [err :: ] (
*** [err :: ] Redis::CannotConnectError
*** [err :: )

```

**Comment by damuz91** [comment]
Any updates ?
