### ISSUE TITLE
websocket-rails standalone mode with Passenger instability

### ISSUE THREAD

**Issue by giolazzareschi** [websocket-rails/websocket-rails#360]
Hello,

I've been using the gem for study purposes about websockets, but I want use it on my projects. I currently have a project runnning and I'm very interested to use it with websocket-rails, but my rails server is Passenger. I've been trying use the gem in standalone mode, but I think that I'm making some mistake on configuration of the standalone mode or, maybe, there is something going wrong with the standalone mode.
My enviroment is:

`OS: CentOS 7 running on Virtualbox, and the rails project is on a shared folder with Windows`
`Server: Passenger with nginx`

I had installed a Redis server, and configured the "websocket_rails.rb" file to connect on Redis:

`config.standalone = true`
`config.standalone_port = 1000`
 `config.redis_options = {:host => 'localhost', :port => '6379'}`

And then start the websocket server properly. I can connect and use it for a while but the problem is that for some reason, after some refreshes on browser the websocket server starts to go down, the file 'tmp/websocket_rails.pid' is removed and the log files shows:

websocket_rails.log

`I [2015-07-20 10:19:26.892] [[32mDispatcher[0m] Event client_connected Finished in 0.007714677 seconds`

`I [2015-07-20 10:19:26.904] [[32mChannel[0m] #<Connection::0b43605af43e20b79cac> subscribed to channel galera`

`I [2015-07-20 10:19:27.182] [[32mSynchronization[0m] Server Removed: mQP0CF0foobURacEyheY2Q`

`E [2015-07-20 10:19:27.211] [[31mDispatcher[0m] Redis::CannotConnectError: Error connecting to Redis on localhost:6379 (Errno::ECONNREFUSED)`

websocket_rails_server.log

`Writing PID to /media/sf_gblfolder/pay/tmp/pids/websocket_rails.pid
/media/sf_gblfolder/pay/config/environments/development.rb:54: warning: already initialized constant OpenSSL::SSL::VERIFY_PEER
Thin web server (v1.6.3 codename Protein Powder)
Maximum connections set to 1024
Listening on 0.0.0.0:1000, CTRL+C to stop
Exiting!`

`/usr/local/rvm/gems/ruby-2.2.1/gems/redis-3.2.1/lib/redis/client.rb:243:in 'rescue in io': Connection lost (ECONNRESET) (Redis::ConnectionError)
	from /usr/local/rvm/gems/ruby-2.2.1/gems/redis-3.2.1/lib/redis/client.rb:236:in 'io'
	from /usr/local/rvm/gems/ruby-2.2.1/gems/redis-3.2.1/lib/redis/client.rb:247:in 'read'
	from /usr/local/rvm/gems/ruby-2.2.1/gems/redis-3.2.1/lib/redis/client.rb:112:in 'block in call'
	from /usr/local/rvm/gems/ruby-2.2.1/gems/redis-3.2.1/lib/redis/client.rb:217:in 'block (2 levels) in process'
	from /usr/local/rvm/gems/ruby-2.2.1/gems/redis-3.2.1/lib/redis/client.rb:353:in 'ensure_connected'
	from /usr/local/rvm/gems/ruby-2.2.1/gems/redis-3.2.1/lib/redis/client.rb:207:in 'block in process'
	from /usr/local/rvm/gems/ruby-2.2.1/gems/redis-3.2.1/lib/redis/client.rb:292:in 'logging'
	from /usr/local/rvm/gems/ruby-2.2.1/gems/redis-3.2.1/lib/redis/client.rb:206:in 'process'
	from /usr/local/rvm/gems/ruby-2.2.1/gems/redis-3.2.1/lib/redis/client.rb:112:in 'call'
	from /usr/local/rvm/gems/ruby-2.2.1/gems/redis-3.2.1/lib/redis.rb:1846:in 'block in hset'
	from /usr/local/rvm/gems/ruby-2.2.1/gems/redis-3.2.1/lib/redis.rb:37:in 'block in synchronize'
	from /usr/local/rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/monitor.rb:211:in 'mon_synchronize'
	from /usr/local/rvm/gems/ruby-2.2.1/gems/redis-3.2.1/lib/redis.rb:37:in 'synchronize'
	from /usr/local/rvm/gems/ruby-2.2.1/gems/redis-3.2.1/lib/redis.rb:1845:in 'hset'
	from /usr/local/rvm/gems/ruby-2.2.1/gems/websocket-rails-0.7.0/lib/websocket_rails/synchronization.rb:154:in 'block in register_user' `

And I have to start server again, and when I try do reconnect the problem stand still.

Someone have faced some related problem? Anyone have a clue? I can provide any further information, any help will be apreciated.

Regards!

**Comment by pyro2927** [comment]
I'm having a similar problem when running clustered websocket rails servers all connected to a single redis instance.

**Comment by giolazzareschi** [comment]
Hi @pyro2927 ,

I've been workin gon this issue in my workspace, and could solve a lot of problems related with stability with this version here:

[websocket-rails updated version: 0.7.0](https://github.com/moaa/websocket-rails)

I think that this gem is no longer updated or matained, but It'll be usefull for you.

Also, you can try solution using Rails 5 ActionCable (kinda native ws support, but it's already released for public tests). You can found it here [ActionCable Rails5 gem exaplained](http://nithinbekal.com/posts/rails-action-cable/)

Bests coding for you, regards.

**Comment by Qqwy** [comment]
You might want to check out #362, as I tried to solve the same problem you have.
