### ISSUE TITLE
Socket is not a module (TypeError)

### ISSUE THREAD

**Issue by csvwolf** [websocket-rails/websocket-rails#365]
Ruby 2.2.1 Rails 4.2.1
When I run:`rails g websocket_rails:install`

Errors comes:
```
/Users/SkyAo/Documents/Coding/Ruby/socket/config/application.rb:9:in `<top (required)>': Socket is not a module (TypeError)
	from /usr/local/lib/ruby/gems/2.2.0/gems/spring-1.3.6/lib/spring/application.rb:82:in `require'
	from /usr/local/lib/ruby/gems/2.2.0/gems/spring-1.3.6/lib/spring/application.rb:82:in `preload'
	from /usr/local/lib/ruby/gems/2.2.0/gems/spring-1.3.6/lib/spring/application.rb:143:in `serve'
	from /usr/local/lib/ruby/gems/2.2.0/gems/spring-1.3.6/lib/spring/application.rb:131:in `block in run'
	from /usr/local/lib/ruby/gems/2.2.0/gems/spring-1.3.6/lib/spring/application.rb:125:in `loop'
	from /usr/local/lib/ruby/gems/2.2.0/gems/spring-1.3.6/lib/spring/application.rb:125:in `run'
	from /usr/local/lib/ruby/gems/2.2.0/gems/spring-1.3.6/lib/spring/application/boot.rb:18:in `<top (required)>'
	from /usr/local/Cellar/ruby/2.2.1/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /usr/local/Cellar/ruby/2.2.1/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from -e:1:in `<main>'
```

Is the version not supported?

**Comment by csvwolf** [comment]
T^T Sorry, It can run now

**Comment by andreyshade** [comment]
How did you solve this issue?

**Comment by andreyshade** [comment]
I solve this issue. Never use in you project name reserved words like "Socket" and etc.
