### ISSUE TITLE
Deploying app on AWS Elastic Beanstalk on Ruby 2.2 Puma

### ISSUE THREAD

**Issue by rwu1997** [websocket-rails/websocket-rails#387]
I was wondering if anyone managed to get websockets to work on AWS EB running Ruby 2.2 Puma, or any similar versions.

I seem to be having issues with EventMachine. The client is spitting out the usual `WebSocket connection to 'ws://my_site_url/websocket' failed: Error during WebSocket handshake: Unexpected response code: 500`. 

I checked `production.log` and the culprit seems to be 
```
RuntimeError (eventmachine not initialized: evma_install_oneshot_timer):
  eventmachine (1.0.8) lib/eventmachine.rb:331:in `add_oneshot_timer'
  eventmachine (1.0.8) lib/eventmachine.rb:331:in `add_timer'
  eventmachine (1.0.8) lib/em/timers.rb:50:in `schedule'
  eventmachine (1.0.8) lib/em/timers.rb:37:in `initialize'
```

I've already added `Thread.new { EventMachine.run } unless EventMachine.reactor_running? && EventMachine.reactor_thread.alive?` to `config/initializers/eventmachine.rb`, but it still produces the same error. 

I've read somewhere that I also need to change the `Upgrade` headers in nginx config, but I'm not exactly sure how to do that with EB.

**Comment by wai-chuen** [comment]
In case you're still after a solution, this is what got it working for me (AWS EB, Puma + Nginx):

The following code goes in a .config file in the /.ebextensions folder. This works for a single instance (i.e. no elastic load balancer). 

More work is needed to get ELB working with websockets, tutorials here:
http://blog.seafuj.com/using-elb-with-websockets

```
files:
  "/etc/nginx/conf.d/000websockets.conf" :
    mode: "000755"
    owner: root
    group: root
    content: |
      server {
        listen 80;
        server_name localhost; # need to listen to localhost for worker tier

        location / {
          proxy_pass http://my_app; # match the name of upstream directive which is defined above
          proxy_set_header Host $host;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }

        location /websocket {
          proxy_pass http://my_app/websocket;
          proxy_set_header Host $host;
          proxy_http_version 1.1;
          proxy_set_header Upgrade $http_upgrade;
          proxy_set_header Connection Upgrade;
        }

        location /assets {
          alias /var/app/current/public/assets;
          gzip_static on;
          gzip on;
          expires max;
          add_header Cache-Control public;
        }

        location /public {
          alias /var/app/current/public;
          gzip_static on;
          gzip on;
          expires max;
          add_header Cache-Control public;
        }
      }

```

**Comment by yellowsun** [comment]
It's still not working. I always get this error message when accessing http://.../websocket: "An unhandled lowlevel error occurred. The application logs may have details.", but my app http://... works perfectly. I already updated my_app to my application name, but it doesn't help. The production.log just says "Started GET "/websocket" for....". What's wrong, please help me correct?

Thank you,

**Comment by MythicalFish** [comment]
Did you find a solution?

**Comment by richardwu** [comment]
Unfortunately no. I would recommend checking out Rails 5 and ActionCable though.
